DELETE http://localhost:8000/member/passenger/delete/1816446392453959680
Content-Type: application/x-www-form-urlencoded
token: {{token}}

###
GET http://localhost:8000/member/passenger/query-list?page=1&size=2
Accept: application/json
token: {{token}}

###
POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "id":1816446392453959680,
  "memberId":1815730042693619712,
  "name": "zhangsan8",
  "idCard": "123321",
  "type": "2"
}

